[package]
name = "moax-dct-swap"
version = "0.0.0"
edition = "2018"
publish = false

[lib]
path = "src/swap.rs"


[dependencies.dharitri-wasm]
version = "0.4.8"
path = "../../../dharitri-wasm"

[dev-dependencies.dharitri-wasm-debug]
version = "0.4.8"
path = "../../../dharitri-wasm-debug"
