[package]
name = "erc1155-meta"
version = "0.0.0"
authors = ["Dorin Iancu <dorin.iancu@dharitri.com>"]
edition = "2018"
publish = false

[dependencies.erc1155]
path = ".."

[dependencies.dharitri-wasm-debug]
version = "0.4.8"
path = "../../../../../dharitri-wasm-debug"
